---
title: "Variation In Weight Between Chaffinch Sexes"
author: "Ellie Kewin"
date: "04/11/2020"
output: 
  bookdown::pdf_document2: default
  bookdown::word_document2: default
  bookdown::html_document2: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3)
```
```{r packages and functions}
library(tidyverse)
library(bookdown)
library(janitor)

sum_sq <- function(df, measure, group) {
  df %>% group_by({{ group }}) %>% 
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}
#function that summarises, the mean, n, standard deviation and standard error of the data
data_summary <- function(df, measure, group)  {
  df %>% 
   group_by({{ group }}) %>% 
   summarise(mean_index = mean({{ measure }}),
            n = length({{ measure }}),  sd = sd({{ measure }}), se = sd/sqrt(n))
  }
```
# Introduction

# Methods
```{r imports}
#Data Import
# the data is organised into two columns, one for each sex
chaff <- read.delim("~/Documents/Uni/Data Science/Chaff/raw_data/chaff.txt") %>%
  janitor::clean_names()
View(chaff)
```

```{r tidy}
#put the data in a tidy format
chaff2 <- chaff %>% 
  pivot_longer(names_to = "sex", 
               values_to = "mass",
               cols = c(1,2))
```    
 
######################### **Data Analysis** ###########################
sum_sq(chaff2, mass, sex)
chaffsummary <- data_summary(chaff2, mass, sex)
    

file <-  "Processed_data/chaff2.txt"
write.table(chaff2, 
            file, 
            quote = FALSE,
            row.names = FALSE)
file <-  "Processed_data/chaffsummary.txt"
write.table(chaffsummary, 
            file, 
            quote = FALSE,
            row.names = FALSE)